#!/usr/bin/with-contenv bash

[[ ! -d /app/sickbeard/.git ]] && (git clone git://github.com/midgetspy/Sick-Beard.git /app/sickbeard && \
chown -R mab:mab /app /config)

# opt out for autoupdates
[ "$ADVANCED_DISABLEUPDATES" ] && exit 0

cd /app/sickbeard
git pull
chown -R mab:mab /app /config
